version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: streamflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: streamflow-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # This configuration works for Docker running on localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zipkin:
    image: openzipkin/zipkin
    container_name: streamflow-zipkin
    ports:
      - "9411:9411"
  redis:
    image: redis:alpine
    container_name: streamflow-redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    container_name: streamflow-mongodb
    ports:
      - "27017:27017"